pipeline {
  agent any

  environment {
    AWS_REGION = "ap-south-1"
    ECR_REPO   = "908692150527.dkr.ecr.ap-south-1.amazonaws.com/order-service"
    IMAGE_TAG  = "${BUILD_NUMBER}"
  }

  stages {

    stage('Checkout Source Code') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('apps/order-service') {
          sh '''
            docker build -t order-service:${IMAGE_TAG} .
          '''
        }
      }
    }

    stage('Login to AWS ECR') {
      steps {
        sh '''
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ECR_REPO
        '''
      }
    }

    stage('Tag & Push Image to ECR') {
      steps {
        sh '''
          docker tag order-service:${IMAGE_TAG} $ECR_REPO:${IMAGE_TAG}
          docker push $ECR_REPO:${IMAGE_TAG}
        '''
      }
    }

  }
}
