pipeline {
  agent any

  stages {

    stage('Checkout Source Code') {
      steps {
        /*
          Pull the latest code from GitHub.
          Jenkins already knows which repo triggered the job.
        */
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        /*
          Move into order-service directory
          because the Dockerfile lives here.
        */
        dir('apps/order-service') {
          sh '''
            docker build -t order-service:${BUILD_NUMBER} .
          '''
        }
      }
    }

    stage('Verify Image') {
      steps {
        /*
          Lightweight verification that the image
          was built and tagged successfully.
        */
        sh '''
          docker images | grep order-service
        '''
      }
    }

  }
}
