apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: user-service-tls
  namespace: apps
spec:
  secretName: user-service-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - user.projectbyradhe.xyz
