pipeline {
  agent any

  stages {

    stage('Checkout Source Code') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        /*
          We must move into the service directory
          because the Dockerfile lives here.
        */
        dir('apps/user-service') {
          sh '''
            docker build -t user-service:${BUILD_NUMBER} .
          '''
        }
      }
    }

    stage('Verify Image') {
      steps {
        sh '''
          docker images | grep user-service
        '''
      }
    }

  }
}

