pipeline {
  agent any

  environment {
    AWS_REGION = "ap-south-1"
    ECR_REPO   = "908692150527.dkr.ecr.ap-south-1.amazonaws.com/product-service"
    IMAGE_TAG  = "${BUILD_NUMBER}"
  }

  stages {

    stage('Checkout Source Code') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('apps/product-service') {
          sh 'docker build -t product-service:${IMAGE_TAG} .'
        }
      }
    }

    stage('Login to AWS ECR') {
      steps {
        sh '''
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ECR_REPO
        '''
      }
    }

    stage('Push Image to ECR') {
      steps {
        sh '''
          docker tag product-service:${IMAGE_TAG} $ECR_REPO:${IMAGE_TAG}
          docker push $ECR_REPO:${IMAGE_TAG}
        '''
      }
    }

    stage('Update GitOps Repo') {
      steps {
        sh '''
          rm -rf gitops
          git clone git@github.com:theradheshyampatil/micro-gitops-platform-gitops.git gitops

          cd gitops/apps/product-service

          sed -i "s|image: .*|image: ${ECR_REPO}:${IMAGE_TAG}|" deployment.yaml

          git config user.name "jenkins"
          git config user.email "jenkins@ci.local"

          if git diff --quiet; then
            echo "No GitOps change required (image already up to date)"
            exit 0
          fi

          git add deployment.yaml
          git commit -m "ci: deploy product-service ${IMAGE_TAG}"
          git push origin main
        '''
      }
    }

  }
}
