pipeline {
  agent any

  environment {
    AWS_REGION = "ap-south-1"
    AWS_ACCOUNT_ID = "908692150527"
    SERVICE_NAME = "product-service"

    IMAGE_TAG = "${BUILD_NUMBER}"
    ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    IMAGE = "${ECR_REGISTRY}/${SERVICE_NAME}:${IMAGE_TAG}"

    GITOPS_REPO = "git@github.com:theradheshyampatil/micro-gitops-platform-gitops.git"
  }

  stages {

    stage('Checkout Source Code') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        dir("apps/${SERVICE_NAME}") {
          sh "docker build -t ${SERVICE_NAME}:${IMAGE_TAG} ."
        }
      }
    }

    stage('Login to AWS ECR') {
      steps {
        sh """
          aws ecr get-login-password --region ${AWS_REGION} |
          docker login --username AWS --password-stdin ${ECR_REGISTRY}
        """
      }
    }

    stage('Push Image to ECR') {
      steps {
        sh """
          docker tag ${SERVICE_NAME}:${IMAGE_TAG} ${IMAGE}
          docker push ${IMAGE}
        """
      }
    }

stage('Update GitOps Repo') {
  steps {
    sh '''
      rm -rf gitops
      git clone git@github.com:theradheshyampatil/micro-gitops-platform-gitops.git gitops

      cd gitops/apps/product-service

      sed -i "s|image: .*|image: ${ECR_REPO}:${IMAGE_TAG}|" deployment.yaml

      git config user.name "jenkins"
      git config user.email "jenkins@ci.local"

      if git diff --quiet; then
        echo "No GitOps change required (image already updated)"
        exit 0
      fi

      git add deployment.yaml
      git commit -m "ci: deploy product-service ${IMAGE_TAG}"
      git push origin main
    '''
  }
}
